[package]
name = "glm-engine"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
glm-cache = { path = "../glm-cache" }
glm-format = { path = "../glm-format" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
